#!/usr/bin/env python3
"""Reproduce the compact OFL monospace fallback. Requires fontTools."""
import argparse,hashlib,io,json,urllib.request
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

COMMIT='895ec691990d041dd727c7b5afa3ce56525d98e6'
BASE=f'https://raw.githubusercontent.com/googlefonts/RobotoMono/{COMMIT}/'
STYLES=('Regular','Bold','Italic','BoldItalic')
SOURCE_SHA256 = {
 'OFL.txt': '50ab8dd54680d3473f649c9db86fece88434d097c7834475c1c72d2f8c429215',
 'RobotoMono-Regular.otf': '874671c3f088802a915e3f7b1b773d3d031e04a21d82e2eb5107aa1c51895c21',
 'RobotoMono-Bold.otf': 'ec4ae3dba5aec385c8b35970c367ec21fb439f3bd15ce7a2a6ab934bc1e67d40',
 'RobotoMono-Italic.otf': '033227ce2ead387fed55baab76b123d57c1c646dd5398c7ef03544cf7053a872',
 'RobotoMono-BoldItalic.otf': 'e15c4bf9a4ad77d1a6aae87d2623eb457c22550600108f34dbec0ed8ad7586e3',
}
CODEPOINTS=set(range(0x20,0x100))|{0x131,0x152,0x153,0x178,0x192,0x2c6,0x2dc,0x3bc,0x2010,0x2011,0x2012,0x2013,0x2014,0x2018,0x2019,0x201a,0x201c,0x201d,0x201e,0x2020,0x2021,0x2022,0x2026,0x2030,0x2039,0x203a,0x20ac,0x2122,0x2190,0x2191,0x2192,0x2193,0x2212,0x221e,0x2260,0x2264,0x2265,0xfffd}

def main():
 p=argparse.ArgumentParser(description=__doc__)
 p.add_argument('--cache',type=Path,required=True)
 p.add_argument('--output',type=Path,default=Path(__file__).resolve().parents[1]/'lib/ReaderMono')
 a=p.parse_args();a.cache.mkdir(parents=True,exist_ok=True);a.output.mkdir(parents=True,exist_ok=True)
 def fetch(path):
  local=a.cache/Path(path).name
  if not local.exists(): local.write_bytes(urllib.request.urlopen(BASE+path).read())
  data=local.read_bytes()
  if hashlib.sha256(data).hexdigest() != SOURCE_SHA256[local.name]:
   raise ValueError(f'Source checksum mismatch: {local.name}')
  return data
 license=fetch('OFL.txt');(a.output/'OFL.txt').write_bytes(license)
 manifest={'source':f'https://github.com/googlefonts/RobotoMono/tree/{COMMIT}','unicode':[hex(c) for c in sorted(CODEPOINTS)],'styles':{}}
 for style in STYLES:
  raw=fetch(f'fonts/otf/RobotoMono-{style}.otf');f=TTFont(io.BytesIO(raw),recalcTimestamp=False)
  o=subset.Options();o.recalc_timestamp=False;o.canonical_order=True;o.name_IDs=[0,1,2,3,4,5,6,14,16,17];o.name_legacy=True;o.name_languages=['*'];o.notdef_glyph=True;o.notdef_outline=True
  sub=subset.Subsetter(options=o);sub.populate(unicodes=CODEPOINTS);sub.subset(f)
  for name in f['name'].names:
   if name.nameID in (1,2,3,4,6,16,17):
    text={1:'Witch Mono',2:style,3:f'WitchMono-{style}-1',4:f'Witch Mono {style}',6:f'WitchMono-{style}',16:'Witch Mono',17:style}[name.nameID]
    name.string=text.encode(name.getEncoding())
  for cmap in f['cmap'].tables:
   if cmap.isUnicode() and 0x3f in cmap.cmap: cmap.cmap[0xfffd]=cmap.cmap[0x3f]
  if 'CFF ' in f:
   cff=f['CFF '].cff;cff.fontNames=[f'WitchMono-{style}'];top=cff.topDictIndex[0];top.FamilyName='Witch Mono';top.FullName=f'Witch Mono {style}'
  buf=io.BytesIO();f.save(buf);data=buf.getvalue()
  (a.cache/f'WitchMono-{style}.otf').write_bytes(data)
  lines=[', '.join(f'0x{b:02x}' for b in data[i:i+16]) for i in range(0,len(data),16)]
  (a.output/f'{style}.inc').write_text('// Generated by scripts/build_monospace_fallback.py; SIL OFL 1.1.\n'+',\n'.join(lines)+'\n')
  manifest['styles'][style]={'source_sha256':hashlib.sha256(raw).hexdigest(),'subset_sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data),'glyphs':len(f.getGlyphOrder())}
 (a.output/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
 print(json.dumps(manifest['styles'],indent=2))
if __name__=='__main__':main()
