#!/usr/bin/env python3
"""Generate Unicode default full case maps (Python Unicode 15.1.0).

Run with Python 3.13. No locale-specific or context-sensitive mappings are
encoded here. In particular lowercasing Greek final sigma and Turkic/Lithuanian
language tailoring remain unsupported. ASCII is handled without a lookup.
"""
from pathlib import Path
import unicodedata

if unicodedata.unidata_version != "15.1.0":
    raise SystemExit("Use Python with Unicode 15.1.0 to reproduce these tables")

out = ["// Generated by scripts/generate_unicode_case.py; Unicode 15.1.0. Do not edit.",
       "#pragma once", "namespace utf8_case_detail {",
       "struct Mapping { uint32_t codepoint; const char* text; };"]
for operation in ("upper", "lower"):
    out.append(f"inline constexpr Mapping {operation}Mappings[] = {{")
    for cp in range(0x80, 0x110000):
        text = getattr(chr(cp), operation)()
        if text != chr(cp):
            escaped = "".join(f"\\x{byte:02x}" for byte in text.encode("utf-8"))
            out.append(f'  {{0x{cp:x}, "{escaped}"}},')
    out.append("};")
out.append("}  // namespace utf8_case_detail")
Path(__file__).resolve().parents[1].joinpath("lib/Utf8/Utf8CaseData.h").write_text("\n".join(out) + "\n")
